import {BookOpen, Code2, Download, FileJson2, LoaderCircle, NotebookTabs, PackageCheck, X} from 'lucide-react';

import {MessageMarkdown, type MarkdownResultLink} from '../message-markdown.js';
import type {ResultDocument} from '../types.js';

export function ReportWorkbench({
  document,
  loading,
  markdown,
  error,
  resources,
  resultLinks,
  onOpenResource = () => undefined,
  onClose,
}: {
  document: ResultDocument | null;
  loading: boolean;
  markdown: string;
  error: string | null;
  resources: Array<{name: string; label: string; url: string; mimeType: string}>;
  resultLinks?: MarkdownResultLink[];
  onOpenResource?: (resource: {name: string; label: string; url: string; mimeType: string}) => void;
  onClose: () => void;
}): React.JSX.Element {
  const figures = resources.filter((resource) => resource.mimeType.startsWith('image/'));
  const packageResources = resources.filter((resource) => !resource.mimeType.startsWith('image/'));
  return <aside className="result-workbench report-workbench" aria-label="Research Report Workbench">
    <header><div><BookOpen size={18} /><span><strong>Research Report</strong><small>{document?.title ?? 'Select a Report'}</small></span></div>{document ? <button onClick={onClose} title="Close Workbench"><X size={17} /></button> : null}</header>
    <div className="result-workbench-body">
      {!document ? <div className="workbench-empty"><BookOpen size={38} /><h2>Review the evidence</h2><p>Open a Research report from an OceanX answer to inspect its conclusions, exact method, and executable record.</p></div> : loading ? <div className="workbench-empty"><LoaderCircle className="spin" size={30} /><p>Loading report…</p></div> : error ? <div className="workbench-error"><strong>Report unavailable</strong><p>{error}</p></div> : <div className="report-scroll"><article className="report-document"><MessageMarkdown content={markdown} resultLinks={resultLinks} /></article>{figures.length ? <section className="report-figures" aria-label="Report figures"><header><h3>Figures</h3><p>Visual evidence generated by the recorded Expert Session.</p></header>{figures.map((figure) => <figure key={figure.name}><img src={figure.url} alt={figure.label} /><figcaption><strong>{figure.label}</strong><a href={figure.url} download={figure.name}>Download image</a></figcaption></figure>)}</section> : null}{packageResources.length ? <section className="report-resources"><h3>Reproducibility package</h3><p>The notebook below is the executed notebook, not a reconstructed example.</p>{packageResources.map((resource) => <button key={resource.name} type="button" onClick={() => onOpenResource(resource)}>{resource.name.endsWith('.ipynb') ? <NotebookTabs size={17} /> : resource.name.endsWith('.py') ? <Code2 size={17} /> : resource.name.endsWith('requirements.txt') ? <PackageCheck size={17} /> : resource.name.endsWith('.json') ? <FileJson2 size={17} /> : <Download size={17} />}<span><strong>{resource.label}</strong><small>{resource.name}</small></span></button>)}</section> : null}</div>}
      {document ? <footer><span>{document.summary}</span><code>{document.key}</code></footer> : null}
    </div>
  </aside>;
}
